name: alkali
version: 0.0.1
author: Jace Hensley
description: UI framework inspired by React.js
hompage: https://github.com/jacehensley/alkali
dependencies:
  browser: '>=0.10.0 <0.11.0'
dev_dependencies:
  benchmark_harness: '^1.0.4'
  coverage: '^0.7.2'
  dart_dev: '^1.0.6'
  mockito: '^0.11.0'
  react: '^0.8.5'
  test: '^0.12.7'
